### ISSUE TITLE
Enable ability to use "Persistent" config that will ensure that non-persisted fields are not returned to camunda

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Formio#9]
![persistent](https://user-images.githubusercontent.com/1994838/32960602-850321c2-cb93-11e7-9fb9-0f759569357d.png)

This is a dual review:

1. Review what we can do to enable this with formio.  CUrrent issue is that this validation is only returned when you save the data into mongo.

2. Should the Mircoservice make this data review?  First thoughts are that "no" it should not.  Formio would just return the data object which would be returned to camunda.

**Comment by StephenOTT** [comment]
Reference https://github.com/formio/formio/issues/454

**Comment by StephenOTT** [comment]
Current workaround is to use latest release of Formio and delete the `save submission` "Form Action" when configuring a formio form.

**Comment by StephenOTT** [comment]
#7 is blocking this issue

**Comment by StephenOTT** [comment]
#7 has been closed/completed.  Issue is unblocked ✅

**Comment by mario-digitalstate** [comment]
Done.
